service: code-review-reminder-course-dev
frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    PADDLE_API_KEY: ${env:PADDLE_API_KEY}
    PADDLE_WEBHOOK_SECRET_KEY: ${env:PADDLE_WEBHOOK_SECRET_KEY}
    STAGE: ${opt:stage, self:custom.defaultStage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "codeReviewReminderBotConfigsTable", "Arn" ] }
        - { "Fn::GetAtt": [ "codeReviewReminderBotSlackInstallsTable", "Arn" ] }
        - { "Fn::GetAtt": [ "codeReviewReminderBotSubscriptionsTable", "Arn" ] }
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
      - http:
          method: get
          path: /slack/install
      - http:
          method: get
          path: /slack/oauth_redirect
  paddle:
    handler: app.paddleHandler
    events:
      - http:
          path: paddle/webhooks
          method: post
custom:
  defaultStage: dev
resources:
  Resources: # CloudFormation template syntax from here on.
    codeReviewReminderBotConfigsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: codeReviewReminderBotConfigs
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
          - AttributeName: record_type
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
          - AttributeName: record_type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    codeReviewReminderBotSlackInstallsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: codeReviewReminderBotSlackInstalls
        AttributeDefinitions:
          - AttributeName: team_or_enterprise_id
            AttributeType: S
          - AttributeName: installation_type
            AttributeType: S
        KeySchema:
          - AttributeName: installation_type
            KeyType: HASH
          - AttributeName: team_or_enterprise_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    codeReviewReminderBotSubscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: codeReviewReminderBotSubscriptions
        AttributeDefinitions:
          - AttributeName: paddle_customer_id
            AttributeType: S
        KeySchema:
          - AttributeName: paddle_customer_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
plugins:
  - serverless-offline
  - serverless-dotenv-plugin