service: code-review-reminder-course-dev
frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    STAGE: ${opt:stage, self:custom.defaultStage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "codeReviewReminderBotConfigsTable", "Arn" ] }
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
custom:
  defaultStage: dev
resources:
  Resources: # CloudFormation template syntax from here on.
    codeReviewReminderBotConfigsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: codeReviewReminderBotConfigs
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
          - AttributeName: record_type
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
          - AttributeName: record_type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
plugins:
  - serverless-offline
  - serverless-dotenv-plugin